### ISSUE TITLE
this repo sucks!

### ISSUE THREAD

**Issue by taboularasa** [pgdaniel/hidavid#2]
:hankey:

**Comment by jadengore** [comment]
@pgdaniel I think we should lock this conversation, seems to be going nowhere...

**Comment by taboularasa** [comment]
@jadengore theres nothing wrong with this issue.

**Comment by pgdaniel** [comment]
It's more better now :hamburger:

**Comment by jadengore** [comment]
10/10

**Comment by taboularasa** [comment]
you missed a bug, left comment
